### ISSUE TITLE
Can the a field used in the fields input be a String Array?

### ISSUE THREAD

**Issue by sferoze** [matteodem/meteor-easy-search#302]
Here is an example schema

```
text:
  type: String
title:
  type: String
tags:
  type: [String]
```

As you can see text and title are plain strings. But tags is an array of string.

When creating an easy search index like so
```
EasySearch.createSearchIndex 'notes',
  field: ['text', 'title']
```
I am currently using `text` and `title` which work fine.

But I am not sure if adding `tags` parameter is working. 

Can one of the fields, used in the index, be a field which is an array of Strings?
